# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
State.destroy_all
Park.destroy_all

# 50.times do |index|
#   State.create!(state_name: Faker::Address.state)
#   end
# p "Created #{State.count} state names."

State.create!(state_name: 'Alabama')
State.create!(state_name: 'Alaska')
State.create!(state_name: 'Arizona')
State.create!(state_name: 'Arkansas')
State.create!(state_name: 'California')
State.create!(state_name: 'Colorado')
State.create!(state_name: 'Connecticut')
State.create!(state_name: 'Delaware')
State.create!(state_name: 'Florida')
State.create!(state_name: 'Georgia')
State.create!(state_name: 'Hawaii')
State.create!(state_name: 'Idaho')
State.create!(state_name: 'Illinois')
State.create!(state_name: 'Indiana')
State.create!(state_name: 'Iowa')
State.create!(state_name: 'Kansas')
State.create!(state_name: 'Kentucky')
State.create!(state_name: 'Louisiana')
State.create!(state_name: 'Maine')
State.create!(state_name: 'Maryland')
State.create!(state_name: 'Massachusetts')
State.create!(state_name: 'Michigan')
State.create!(state_name: 'Minnesota')
State.create!(state_name: 'Mississippi')
State.create!(state_name: 'Missouri')
State.create!(state_name: 'Montana')
State.create!(state_name: 'Nebraska')
State.create!(state_name: 'Nevada')
State.create!(state_name: 'New Hampshire')
State.create!(state_name: 'New Jersey')
State.create!(state_name: 'New Mexico')
State.create!(state_name: 'New York')
State.create!(state_name: 'North Carolina')
State.create!(state_name: 'North Dakota')
State.create!(state_name: 'Ohio')
State.create!(state_name: 'Oklahoma')
State.create!(state_name: 'Oregon')
State.create!(state_name: 'Pennsylvania')
State.create!(state_name: 'Rhode Island')
State.create!(state_name: 'South Carolina')
State.create!(state_name: 'South Dakota')
State.create!(state_name: 'Tennessee')
State.create!(state_name: 'Texas')
State.create!(state_name: 'Utah')
State.create!(state_name: 'Vermont')
State.create!(state_name: 'Virginia')
State.create!(state_name: 'Washington')
State.create!(state_name: 'West Virginia')
State.create!(state_name: 'Wisconsin')
State.create!(state_name: 'Wyoming')

Park.create!(parks_name: "Denali National Park", state_id: 2)
Park.create!(parks_name: "Gates of the Arctic National Park", state_id: 2)
Park.create!(parks_name: "Glacier Bay National Park", state_id: 2)
Park.create!(parks_name: "Katmai National Park", state_id: 2)
Park.create!(parks_name: "Kenai Fjords National Park", state_id: 2)
Park.create!(parks_name: "Kobuk Valley National Park", state_id: 2)
Park.create!(parks_name: "Lake Clark National Park", state_id: 2)
Park.create!(parks_name: "Wrangell-St. Elias National Park", state_id: 2)
Park.create!(parks_name: "Grand Canyon National Park", state_id: 3)
Park.create!(parks_name: "Petrified Forest National Park", state_id: 3)
Park.create!(parks_name: "Saguaro National Park", state_id: 3)
Park.create!(parks_name: "Hot Springs National Park", state_id: 4)
Park.create!(parks_name: "Channel Islands National Park", state_id: 5)
Park.create!(parks_name: "Death Valley National Park", state_id: 5)
Park.create!(parks_name: "Joshua Tree National Park", state_id: 5)
Park.create!(parks_name: "Kings Canyon National Park", state_id: 5)
Park.create!(parks_name: "Lassen Volcanic National Park", state_id: 5)
Park.create!(parks_name: "Pinnacles National Park", state_id: 5)
Park.create!(parks_name: "Redwood National Park", state_id: 5)
Park.create!(parks_name: "Sequoia National Park", state_id: 5)
Park.create!(parks_name: "Yosemite National Park", state_id: 5)
Park.create!(parks_name: "Black Canyon of the Gunnison National Park", state_id: 6)
Park.create!(parks_name: "Great Sand Dunes National Park", state_id: 6)
Park.create!(parks_name: "Mesa Verde National Park", state_id: 6)
Park.create!(parks_name: "Rocky Mountain National Park", state_id: 6)
Park.create!(parks_name: "Biscayne National Park", state_id: 9)
Park.create!(parks_name: "Dry Tortugas National Park", state_id: 9)
Park.create!(parks_name: "Everglades National Park", state_id: 9)
Park.create!(parks_name: "Haleakalā National Park", state_id: 11)
Park.create!(parks_name: "Hawai'i Volcanoes National Park", state_id: 11)
Park.create!(parks_name: "Yellowstone National Park", state_id: 12)
Park.create!(parks_name: "Gateway Arch National Park", state_id: 13)
Park.create!(parks_name: "Indiana Dunes National Park", state_id: 14)
Park.create!(parks_name: "Mammoth Cave National Park", state_id: 17)
Park.create!(parks_name: "Acadia National Park", state_id: 19)
Park.create!(parks_name: "Isle Royale National Park", state_id: 22)
Park.create!(parks_name: "Voyageurs National Park", state_id: 23)
Park.create!(parks_name: "Gateway Arch National Park", state_id: 25)
Park.create!(parks_name: "Glacier National Park", state_id: 26)
Park.create!(parks_name: "Yellowstone National Park", state_id: 26)
Park.create!(parks_name: "Death Valley National Park", state_id: 28)
Park.create!(parks_name: "Great Basin National Park", state_id: 28)
Park.create!(parks_name: "Carlsbad Caverns National Park", state_id: 31)
Park.create!(parks_name: "Great Smoky Mountains National Park", state_id: 33)
Park.create!(parks_name: "Theodore Roosevelt National Park", state_id: 34)
Park.create!(parks_name: "Cuyahoga Valley National Park", state_id: 35)
Park.create!(parks_name: "Crater Lake National Park", state_id: 37)
Park.create!(parks_name: "Congaree National Park", state_id: 40)
Park.create!(parks_name: "Wind Cave National Park", state_id: 41)
Park.create!(parks_name: "Great Smoky Mountains National Park", state_id: 42)
Park.create!(parks_name: "Big Bend National Park", state_id: 43)
Park.create!(parks_name: "Guadalupe Mountains National Park", state_id: 43)
Park.create!(parks_name: "Zion National Park", state_id: 44)
Park.create!(parks_name: "Arches National Park", state_id: 44)
Park.create!(parks_name: "Bryce Canyon National Park", state_id: 44)
Park.create!(parks_name: "Canyonlands National Park", state_id: 44)
Park.create!(parks_name: "Capitol Reef National Park", state_id: 44)
Park.create!(parks_name: "Shenandoah National Park", state_id: 46)
Park.create!(parks_name: "Mount Rainier National Park", state_id: 47)
Park.create!(parks_name: "North Cascades National Park", state_id: 47)
Park.create!(parks_name: "Olympic National Park", state_id: 47)
Park.create!(parks_name: "Grand Teton National Park", state_id: 50)
Park.create!(parks_name: "Yellowstone National Park", state_id: 50)
