# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
State.destroy_all
Park.destroy_all

# 50.times do |index|
#   State.create!(state_name: Faker::Address.state)
#   end
# p "Created #{State.count} state names."

State.create!(state_name: 'Alabama')
State.create!(state_name: 'Alaska')
State.create!(state_name: 'Arizona')
State.create!(state_name: 'Arkansas')
State.create!(state_name: 'California')
State.create!(state_name: 'Colorado')
State.create!(state_name: 'Connecticut')
State.create!(state_name: 'Delaware')
State.create!(state_name: 'Florida')
State.create!(state_name: 'Georgia')
State.create!(state_name: 'Hawaii')
State.create!(state_name: 'Idaho')
State.create!(state_name: 'Illinois')
State.create!(state_name: 'Indiana')
State.create!(state_name: 'Iowa')
State.create!(state_name: 'Kansas')
State.create!(state_name: 'Kentucky')
State.create!(state_name: 'Louisiana')
State.create!(state_name: 'Maine')
State.create!(state_name: 'Maryland')
State.create!(state_name: 'Massachusetts')
State.create!(state_name: 'Michigan')
State.create!(state_name: 'Minnesota')
State.create!(state_name: 'Mississippi')
State.create!(state_name: 'Missouri')
State.create!(state_name: 'Montana')
State.create!(state_name: 'Nebraska')
State.create!(state_name: 'Nevada')
State.create!(state_name: 'New Hampshire')
State.create!(state_name: 'New Jersey')
State.create!(state_name: 'New Mexico')
State.create!(state_name: 'New York')
State.create!(state_name: 'North Carolina')
State.create!(state_name: 'North Dakota')
State.create!(state_name: 'Ohio')
State.create!(state_name: 'Oklahoma')
State.create!(state_name: 'Oregon')
State.create!(state_name: 'Pennsylvania')
State.create!(state_name: 'Rhode Island')
State.create!(state_name: 'South Carolina')
State.create!(state_name: 'South Dakota')
State.create!(state_name: 'Tennessee')
State.create!(state_name: 'Texas')
State.create!(state_name: 'Utah')
State.create!(state_name: 'Vermont')
State.create!(state_name: 'Virginia')
State.create!(state_name: 'Washington')
State.create!(state_name: 'West Virginia')
State.create!(state_name: 'Wisconsin')
State.create!(state_name: 'Wyoming')
